### ISSUE TITLE
Incorrect loading of merge_files option

### ISSUE THREAD

**Issue by sekrell** [SamuelDauzon/Minifpy#2]
When parsing merge_files the wrong settings key is used to load the target files:

https://github.com/SamuelDauzon/Minifpy/blob/2d55c745c8ee957bba65b6e2411ee70f9a6c8ae3/minifpy.py#L202

Shall be changed to "from".

**Comment by SamuelDauzon** [comment]
Thank you for the solution in issue. You've right.
I fixed this here : https://github.com/SamuelDauzon/Minifpy/commit/a29fb69305efe62f36859dd6d00ddeba08e42dbb
